version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports: 
      - "8080:8080"
      - "50000:50000"
    volumes: 
      - C:/Users/Elliott/Documents/GitHub/jenkins/jenkins_home:/var/jenkins_home
    networks:
      - net
  vps:
    container_name: vps
    image: centos-vps
    build: 
      context: centos7
    networks:
      - net
  database:
    container_name: mysql
    image: mysql:5.7
    environment: 
      - "MYSQL_ROOT_PASSWORD=1234"
    volumes: 
      - C:/Users/Elliott/Documents/GitHub/jenkins/mysql_db:/var/lib/mysql
    networks: 
      - net
networks:
  net: